spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_app
    username: root
    password: 1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.example.com
    port: 587
    username: krishna14054@gmail.com
    password: Sai1998@45
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
